import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Algorithm Visualiser",
	description: "Generated by create next app",
	icons: [
		{
			rel: "icon",
            type: "image/png",
            sizes: '32x32',
			url: "/logo.png",
		},
	],
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				cz-shortcut-listen="true"
			>
				<Toaster position="bottom-center" />
				{children}
			</body>
		</html>
	);
}
